# Experiment settings
mode: 'train'
environment_id: 'ICLcar-v0'
seed: 1
num_envs: 1
log_frequency: 5
control_frequency: 60
verbose: True
render: True
use_gpu: True

# Training settings
batch_size: 64
buffer_size: 1000000
num_iterations: 20000
max_episode_length: 1000
noise_stddev: 0.2

# RL Agent settings
tau: 0.001
discount: 0.99
actor_lr: 1e-4
critic_lr: 1e-3
uniform_init: [3e-4, 3e-3]
hidden_sizes: [400, 300]

# Car environment settings
num_range_sensors: 0
center_lane_sensor: 1
lane_curvature_sensor: 0
lane_direction_sensor: 1
crop_size: 200
env_mode: 'rgb_array'
hide_display: True
act_limit: 50

# Spinning up settings
algo: 'ddpg'
epochs: 50
start_steps: 1000
steps_per_epoch: 2000
update_after: 1000
update_every: 50
num_test_episodes: 5

# Logging and model saving
log_dir: 'logs/'
exp_name: 'test'
save_frames: False