# env: 
#   type: FlatEvadeEnv
#   spec: configs/flat_evade_env.yaml

# agents:
#   robot: 
#     type: ModelBasedAgent
#     spec: configs/flat_evade_agent_1.yaml
#   human: 
#     type: ModelBasedAgent
#     spec: configs/flat_evade_agent_2.yaml

env:
  type: FlatEnv
  spec: configs/flat_reach_env.yaml

agents:
  human: 
    type: ModelBasedAgent
    spec: configs/flat_reach_agent_2.yaml
  obs1:
    type: ModelBasedAgent
    spec: configs/flat_reach_obs_1.yaml
  obs2:
    type: ModelBasedAgent
    spec: configs/flat_reach_obs_2.yaml

iters: 200
render: true

debug:
  render_traj: true
  render_next_traj_point: true
  log_traj: false
  log_next_traj_point: false
  log_control: true
  log_agent_state: true
  plot_control: true