# env: 
#   type: FlatEvadeEnv
#   spec: configs/flat_evade_env.yaml

# agents:
#   robot: 
#     type: ModelBasedAgent
#     spec: configs/flat_evade_agent_1.yaml
#   human: 
#     type: ModelBasedAgent
#     spec: configs/flat_evade_agent_2.yaml

# env:
#   type: FlatEnv
#   spec: configs/flat_reach_env.yaml

# agents:
#   human: 
#     type: ModelBasedAgent
#     spec: configs/flat_reach_agent_2.yaml
#   obs1:
#     type: ModelBasedAgent
#     spec: configs/flat_reach_obs_1.yaml
#   obs2:
#     type: ModelBasedAgent
#     spec: configs/flat_reach_obs_2.yaml

env:
  type: FlatEnv
  spec: configs/mas_env.yaml

agents:
  a1:
    type: MASAgent
    spec: configs/mas_sim_a1.yaml
  a2:
    type: MASAgent
    spec: configs/mas_sim_a2.yaml
  a3:
    type: MASAgent
    spec: configs/mas_sim_a3.yaml

obs:
  ob1:
    type: MASAgent
    spec: configs/mas_sim_ob1.yaml

iters: 1000
render: true

debug:
  render_traj: false
  render_next_traj_point: false
  log_traj: false
  log_next_traj_point: false
  log_control: false
  log_agent_state: false
  plot_control: false