name: robot
task:
    type: FlatEvadeTask
    spec: {}
model:
    type: BallModel
    spec:
        dT: 0.02
        control_input_dim: 2
    # type: LinearModel
    # spec:
    #     use_spec: False
    #     use_library: False
    #     model_name: Ballbot
    #     time_sample: 0.02
    #     disc_flag: True
    #     model_spec: null
    #     control_input_dim: 2
estimator:
    type: NaiveEstimator
    spec:
        init_x: [50.0, 20.0, 0.0, 0.0]
        init_variance: [0.01, 0.01, 0.01, 0.01]
        Rww: [0.001, 0.001, 0.001, 0.001]
        Rvv: [0.001, 0.001, 0.001, 0.001]
        alpha_ukf: 1
        kappa_ukf: 0.1
        beta_ukf: 2
        time_sample: 0.01
        kp: 40
        kv: 40
planner:
    type: NaivePlanner
    spec:
        horizon: 20
        replanning_cycle: 10
        dim: 2
        n_ob: 1
        obs_r: 5
controller:
    type: Controller
    spec:
        feedback_controller: 
          type: NaiveFeedbackController
          spec:
            kp: 200
            kv: 50
            u_max: 200
        safe_controller: 
          type: SafeSetController
          spec:
            d_min: 10.0
            k_v: 1.0
            eta: 1
sensors:
-   type: PVSensor
    spec:
        alias: cartesian_sensor
        noise_var: 0.1
-   type: StateSensor
    spec:
        alias: state_sensor
        noise_var: 0.1
-   type: RadarSensor
    spec:
        alias: obstacle_sensor
        noise_var: 0.1
-   type: GoalSensor
    spec:
        alias: goal_sensor
        noise_var: 0.0
-   type: RadioSensor
    spec:
        alias: communication_sensor
