world:
    type: FlatReachingWorld
    spec:
        friction: 0
        reaching_eps: 1
        agent_goal_lists:
            a1: [[20.0, 10.0]]
            a2: [[15.0, 15.0]]
            ob1: [[20.0, 5.0]]
            # a3: [[20.0, 15.0]]
            a3: [[10.0, 5.0]]
            obstat: [[15.0, 10.0]]
dt: 0.02
agent_comp_spec:
    a1: configs/mas_sim_a1.yaml
    a2: configs/mas_sim_a2.yaml
    # ob1: configs/mas_sim/ob1.yaml
    a3: configs/mas_sim_a3.yaml
agent_env_spec:
    a1:
        type: BB8Agent
        spec:
            init_x: [10.0, 10.0, 0.0, 0.0]
    a2:
        type: BB8Agent
        spec:
            init_x: [15.0, 5.0, 0.0, 0.0]
    ob1:
        type: BB8Agent
        spec:
            init_x: [10.0, 15.0, 0.0, 0.0]
    a3:
        type: BB8Agent
        spec:
            # init_x: [10.0, 5.0, 0.0, 0.0]
            init_x: [20.0, 15.0, 0.0, 0.0]
    obstat:
        type: BB8Agent
        spec:
            init_x: [15.0, 10.0, 0.0, 0.0]
