world:
    type: FlatReachingWorld
    spec:
        friction: 0
        reaching_eps: 0.1
        agent_goal_lists:
            a1: [[20.0, 10.0]]
            a2: [[15.0, 15.0]]
    # # todo change spec to:
    # agent_tasks:
    #     robot:
    #         task: FlatEvadeTask
    #         spec:
    #             reaching_eps: 0.1
    #             goal: null
    #     human:
    #         task: FlatEvadeTask
    #         spec:
    #             reaching_eps: 0.1
    #             goal: "robot"
dt: 0.01
agent_comp_spec:
    robot: configs/mas_sim_a1.yaml
    human: configs/mas_sim_a2.yaml
agent_env_spec:
    a1:
        type: BB8Agent
        spec:
            init_x: [10.0, 10.0, 0.0, 0.0]
    a2:
        type: BB8Agent
        spec:
            init_x: [15.0, 5.0, 0.0, 0.0]

# ? it seems that the control (dynamics) model in model-based agent might not be
# ? consistent with the actual simulation agent?
