name: human
task:
    type: FrankaReachingTask
    spec: {}
model:
    type: LinearModel
    spec:
        use_spec: 0
        use_library: 0
        model_name: Ballbot
        time_sample: 0.01
        disc_flag: 1
        model_spec: null
        control_input_dim: 7
estimator:
    type: NaiveEstimator
    spec:
        name: human
        init_x: [1.1, 0.0, 0.0]
        init_variance: [0.01, 0.01, 0.01]
        Rww: [0.001, 0.001, 0.001]
        Rvv: [0.001, 0.001, 0.001]
        alpha_ukf: 1
        kappa_ukf: 0.1
        beta_ukf: 2
        time_sample: 0.1
        kp: 1
        kv: 3
planner:
    type: NaivePlanner
    spec:
        horizon: 20
        replanning_cycle: 10
controller:
    type: NaiveController
    spec:
        kp: 0.5
        kv: 0.1
sensors:
-   type: PVSensor
    spec:
        alias: cartesian_sensor
        noise_var: 0.0
-   type: StateSensor
    spec:
        alias: state_sensor
        noise_var: 0.0
-   type: RadarSensor
    spec:
        alias: obstacle_sensor
        noise_var: 0.0
-   type: GoalSensor
    spec:
        alias: goal_sensor
        noise_var: 0.0
-   type: RadioSensor
    spec:
        alias: communication_sensor
