name: robot
policy:
    type: ActorCriticPolicy
    spec:
        model_path: agent/saved_models/FetchReach-v1/model.pt
        env_params:
            obs: 10
            goal: 3
            action: 4
            action_max: [1.0, 1.0, 1.0, 1.0]
sensors:
-   type: PVSensor
    spec:
        alias: cartesian_sensor
        noise_var: 0.0
-   type: StateSensor
    spec:
        alias: state_sensor
        noise_var: 0.0
-   type: RadarSensor
    spec:
        alias: obstacle_sensor
        noise_var: 0.0
-   type: GoalSensor
    spec:
        alias: goal_sensor
        noise_var: 0.0
-   type: RadioSensor
    spec:
        alias: communication_sensor
