world:
    type: BulletWorld
    spec:
        gravity: 10
        reaching_eps: 0.05
        agent_goal_lists:
            robot: [[0.5, -0.3, 0.2], [0.5, -0.3, 0.4], [0.5, -0.1, 0.2]]
            human: [[0.5, 0.1, 0.5], [0.6, 0.2, 0.2], [0.4, -0.3, 0.5], [0.6, -0.3, 0.2]]
dt: 0.02
agent_env_spec:
    robot:
        type: FrankaPanda
        spec:
            control_space: cartesian
            base_position: [0, 0, 0]
            init_joints: [0, -0.215, 0, -2.57, 0, 2.356, 2.356, 0.08, 0.08]
    human:
        type: Ball
        spec:
            init_position: [1.1, 0, 0.2]
