# todo merge config of CAT-env and 3rd-party env
suite_name: mygoal1
hazards_size: 0.15
world:
    type: FlatReachingWorld
    spec:
        friction: 0
        reaching_eps: 1
        agent_goal_lists:
            # Model based
            robot: null
            # human: null

            # RL
            # 'random'/'static'/'near'
            # robot: 'random'
            # human: 'static'
dt: 0.02
agent_comp_spec:
    robot: configs/safety_gym_agent_1.yaml
    # human: configs/flat_reach_agent_2.yaml
# todo move agent config for env inside world config
agent_env_spec: null

#     robot:
#         type: BB8Agent
#         spec:
#             # All
#             # for specified location
#             init_x: [50.0, 20.0, 0.0, 0.0]

#             # RL
#             # for random location
#             # init_x: null
#             # u_max: [1000, 1000]

#     human:
#         type: BB8Agent
#         spec:
#             # All
#             init_x: [30.0, 20.0, 0.0, 0.0]

#             # RL
#             # init_x: null

